name: dependency-check

on:
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch:

env:
  ENVIRONMENT_FILE: 'example/environment.yml'
  ENVIRONMENT_NAME: 'example'

defaults:
  run:
    shell: bash -el {0}

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          auto-activate-base: true
          activate-environment: ""

      - name: Install Packages
        run: mamba install jake=3.0.0 pandas=1.5.3 tabulate=0.9.0

      - name: Create New Environment
        run: mamba env create --file ${{ env.ENVIRONMENT_FILE }}

      - name: Debug
        run: mamba env list

      - name: Create Jake Report
        run: mamba list -n ${{ env.ENVIRONMENT_NAME }} --explicit | jake ddt -o report.json --output-format json

      - name: Create Issue Body
        run: python .ci-helpers/report.py -i report.json -o issue-body.md
        if: failure()

      - name: Get Current Date
        run: echo "CURRENT_DATE=$(date +'%b %d, %Y')" >> "$GITHUB_ENV"
        if: failure()

      - name: Open New Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Security alert updates (${{ env.CURRENT_DATE }})
          content-filepath: ./issue-body.md
          labels: |
            report
            automated issue
        if: failure()
